@startuml systemOperation
class "System" {

    + accessTerminal(): void
    +loadCSV(file): void
    + setCriteria(depCity, arrCity, trainType, days,\n depFrom?, depTo?, maxPriceFirst?, maxPriceSecond?,\n maxStops=2, minTransfer=10, cls='second', sort='duration'): void
    + executeSearch(): void
    + terminalExited(): void
}
@enduml