@startuml use_case_diagram
left to right direction
actor Client

rectangle "Train Connection System" {
  usecase "UC-01 Load Schedule Data" as UC01
  usecase "UC-02 Search for a Connection" as UC02
  usecase "UC-03 Displayed Results" as UC03
}

Client --> UC01
Client --> UC02



UC02 --> UC03 : <<allows>>

@enduml
